// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
///
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOprxdHRtxKThc6UulT1n0tSAQxZ0UeG0',
    appId: '1:1026068070435:web:351cbf820f61151c78f196',
    messagingSenderId: '1026068070435',
    projectId: 'fir-analytics-1f0e1',
    authDomain: 'fir-analytics-1f0e1.firebaseapp.com',
    storageBucket: 'fir-analytics-1f0e1.appspot.com',
    measurementId: 'G-VBWBJRHVG1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUq_7vXo900m7ZZvw2eYwT7Z8Vgi6CmSI',
    appId: '1:1026068070435:android:1fded63d744f777b78f196',
    messagingSenderId: '1026068070435',
    projectId: 'fir-analytics-1f0e1',
    storageBucket: 'fir-analytics-1f0e1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDV-EfvB6km_Zb88ilau0oB9nB1nLFAb7I',
    appId: '1:1026068070435:ios:c4a310995a1e76d978f196',
    messagingSenderId: '1026068070435',
    projectId: 'fir-analytics-1f0e1',
    storageBucket: 'fir-analytics-1f0e1.appspot.com',
    iosClientId:
        '1026068070435-8gm2cn7kasflfnp22abrs5gme0vtij0j.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseanalytic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDV-EfvB6km_Zb88ilau0oB9nB1nLFAb7I',
    appId: '1:1026068070435:ios:c4a310995a1e76d978f196',
    messagingSenderId: '1026068070435',
    projectId: 'fir-analytics-1f0e1',
    storageBucket: 'fir-analytics-1f0e1.appspot.com',
    iosClientId:
        '1026068070435-8gm2cn7kasflfnp22abrs5gme0vtij0j.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseanalytic',
  );
}
